name: Deploy
on:
    push:
        branches: [main]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
        with:
            host: projects.bijanprogrammer.com
            base-href: /css-animations/
            project-name: css-animations
